# Change these first
owner: SoumyaK4 # Your GitHub organization or username, where this repository lives
repo: Uptime # The name of this repository

sites:
  - name: Portfolio 
    url: https://soumyak4.in/
    maxResponseTime: 500
  - name: Weiqi Roadmap
    url: https://weiqi.soumyak4.in/
    maxResponseTime: 500
  - name: BadukTube
    url: https://baduktube.soumyak4.in/
    maxResponseTime: 20000
  - name: Timeline
    url: https://soumyak4.in/Timeline/
    maxResponseTime: 500
  - name: Association of Indian Go Players
    url: https://aigp.org.in/
    maxResponseTime: 500
  # - name: Indian Go Database
  #   url: https://igd.soumyak4.in/
  #   maxResponseTime: 30000
    
skipDeleteIssues: true

workflowSchedule:
  uptime: "/15 * * * *"        # Uptime checks every hour
  responseTime: "/15 * * * *"  # Response time recording every hour
  staticSite: "0 * * * *"    # Status page rebuild every hour
  summary: "0 * * * *"       # README summary updates every hour
  graphs: "0 * * * *"         # Graph generation every hour

assignees:
  - "SoumyaK4"        
  
status-website:
  cname: status.soumyak4.in
  theme: night
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Site Stats
  introTitle: "[SoumyaK4's](https://soumyak4.in/SiteStats/) Site Uptime Stats"
  # introMessage: Contact Me for Errors
  navbar:
    - title: Linktree
      href: https://soumyak4.in/SiteStats/

  # favicon: https://example.com/favicon.png
  # faviconSvg: https://example.com/logo.svg

  
# See https://upptime.js.org/docs/configuration
