# Change these first
owner: SoumyaK4 # Your GitHub organization or username, where this repository lives
repo: Upptime # The name of this repository

sites:
  - name: Portfolio 
    url: https://soumyak4.in/
    maxResponseTime: 5000
  - name: WeiqiRoadmap
    url: https://weiqi.soumyak4.in/
    maxResponseTime: 5000
  - name: BadukTube
    url: https://baduklectures.soumyak4.in/
    maxResponseTime: 60000
# assignees:
  # - SoumyaK4
skipDeleteIssues: true

status-website:
  cname: status.soumyak4.in
  theme: night
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Site Stats
  introTitle: "**SoumyaK4's** Site Uptime Stats"
  introMessage: Contact Me for Errors
  navbar:
    - title: Status
      href: /Uptime
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

  # favicon: https://example.com/favicon.png
  # faviconSvg: https://example.com/logo.svg

  
# See https://upptime.js.org/docs/configuration
