# Change these first
owner: SoumyaK4 # Your GitHub organization or username, where this repository lives
repo: Uptime # The name of this repository

sites:
  - name: Portfolio 
    url: https://soumyak4.in/
    maxResponseTime: 200
  - name: Weiqi Roadmap
    url: https://weiqi.soumyak4.in/
    maxResponseTime: 200
  - name: BadukTube
    url: https://baduktube.soumyak4.in/about
    maxResponseTime: 5000
  - name: TsumeGod
    url: https://tsumegod.soumyak4.in/
    maxResponseTime: 5000
  - name: Association of Indian Go Players
    url: https://aigp.org.in/
    maxResponseTime: 500
  - name: RhymeTime
    url: https://rhymetime.soumyak4.in/
    maxResponseTime: 200
 - name: Vietnam Go Association 
   url: https://viet-go.soumyak4.in/
   maxResponseTime: 200

# skipDeleteIssues: true

workflowSchedule:
  uptime: "*/30 * * * *"        # Uptime checks every 30m
  responseTime: "*/30 * * * *"  # Response time recording every 30m
  staticSite: "*/30 * * * *"    # Status page rebuild every hour
  summary: "*/30 * * * *"       # README summary updates every hour
  graphs: "*/30 * * * *"         # Graph generation every hour

assignees:
  - "SoumyaK4"        
  
status-website:
  cname: status.soumyak4.in
  theme: night
  logoUrl: https://raw.githubusercontent.com/SoumyaK4/soumyak4.github.io/main/assets/img/Logo.png
  name: SoumyaK4
  introTitle: "[SoumyaK4's](https://soumyak4.in/) Site Uptime Stats"
  # introMessage: Contact Me for Errors
  navbar:
    - title: Profile
      href: https://soumyak4.in/
    - title: Pulsetic
      href: https://pulse.soumyak4.in/

  favicon: https://raw.githubusercontent.com/SoumyaK4/SoumyaK4/main/assets/img/favicons/favicon-96x96.png
  faviconSvg: https://raw.githubusercontent.com/SoumyaK4/SoumyaK4/main/assets/img/favicons/favicon.svg

  
# See https://upptime.js.org/docs/configuration
